stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(echo -n "json_key:${CI_REGISTRY_KEY}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
    # Запуск Kaniko с флагом --force
    - >-
    - /kaniko/executor
      --force
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHORT_SHA}"
      --verbosity=debug
  tags:
    - build

deploy:
  image: mirror.gcr.io/ubuntu
  stage: deploy
  variables:
    ADMIN_INTERFACE_PORT: $ADMIN_INTERFACE_PORT
    ADMIN_LOGIN: $ADMIN_LOGIN
    ADMIN_PASSWORD: $ADMIN_PASSWORD

    TELEGRAM_API_KEY: $TELEGRAM_API_KEY

    POSTGRES_SERVER: $POSTGRES_SERVER
    POSTGRES_PORT: $POSTGRES_PORT
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  script:
  - apt-get update && apt-get install -y curl
  - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  - export PATH=${PATH}:/root/yandex-cloud/bin/
  - curl -fsSL https://raw.githubusercontent.com/tests-always-included/mo/3.1.0/mo -o mo && chmod +x mo
  - head -n1 mo | grep -q '^#!' || { echo "mo download is not a script:"; cat mo; exit 1; }
  - ./mo docker-compose.prod.yml.template > docker-compose.prod.yml
  - echo "${CI_REGISTRY_KEY}" > key.json
  - yc config set service-account-key key.json
  - yc compute instance create-with-container
    --name bot-instance --zone ru-central1-b --folder-id b1g5kgfqtikk024tvq81
    --public-ip=true --create-boot-disk size=30 --service-account-name telegram-bot
    --docker-compose-file docker-compose.prod.yml || true
  - yc compute instance update-container --name bot-instance --folder-id b1g5kgfqtikk024tvq81
    --docker-compose-file docker-compose.prod.yml

  tags:
    - deploy